### ISSUE TITLE
Don't index records with ShowInSearch=false

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-fulltextsearch#257]
The module makes no assumption about what criteria might be applied for records to be added to the index. I'm proposing elsewhere that we [filter out records with anonymous canView=false](https://github.com/silverstripe/silverstripe-fulltextsearch/issues/252). 

In addition, I think we should add behavior to prevent indexing of a record based on custom, model specific flags like `ShowInSearch`. Currently, the docs mention this usage pattern (e.g. https://www.cwp.govt.nz/developer-docs/en/2/features/solr_search/default_search_index/), and recommend adding this as a filter field. You're still in charge of filtering on that field by default. The [CWPSearchEngine](https://github.com/silverstripe/cwp-search/blob/master/src/CwpSearchEngine.php#L61) performs this filter out of the box, but *only* on `SiteTree` and `File` (see [pull request](https://github.com/silverstripe/cwp/pull/64/files#r178983597)). If you're defining your own index on other objects, or include other objects in that index, you need to create your own search engine - the filter field is indexed, but it's ignored during searches. The docs for [searching dataobjects](https://www.cwp.govt.nz/developer-docs/en/2/features/solr_search/searching_dataobjects/) fail to mention that as well. This illustrates why we shouldn't have those records in the index in the first place.

This has some of the same rollout issues as [filter out records with anonymous canView=false](https://github.com/silverstripe/silverstripe-fulltextsearch/issues/252), we'd need to advise devs on how to get those existing index entries with ShowInSearch=false out of their index.

When releasing this, we should strongly recommend to search users that they run a reindex to prune any records with ShowInSearch=0 in their current search state.

Another thing to check: when we change ShowInSearch from 1 to 0 and click save/publish, does it get removed from the index straight away?

### ACs
- [x] Records which have a ShowInSearch method or database property returning false are not indexed
- [x] This applies to built-in records (Page, File) as well as custom record definitions
- [x] This behaviour applies to both CWP and core module search
- [x] The ShowInSearch value is inspected every time a record is saved (non-versioned) or published (versioned), and the index entry is updated accordingly
- [x] Existing index entries with ShowInSearch=0 can be pruned through a reindex
- [x] There is documentation both for CWP and generic module upgrade paths
- [x] Documentation is adjusted to state that you MUST filter out ShowInSearch during search request for safety (rather than reindexing) Steve: users don't need to filter out during search, happens automatically 
- [x] Funtionality for filtering ShowInSearch during search requests is retained in order to minimise risk, but marked as deprecated and non-functional - Steve: have instead deleted functionality from cwp-search module

### Note:
We still have to index the ShowInSearch property, otherwise search request filtering on existing implementations will fail

### PRs:
https://github.com/silverstripe/silverstripe-fulltextsearch/pull/275
https://github.com/silverstripe/cwp/pull/260
https://github.com/silverstripe/cwp-search/pull/31

### Subtasks
- [x] Work out central place to add $this->addFilterField('ShowInSearch') so that it's available in core
- [x] Investigate where solr index is being updated so that we can also delete from there
- [x] Test also works for getShowInSearch() (it does, comments below)
- [x] Investigate filtering solr outlet on DataObject.ShowInSearch (for sites that have not reindexed)
- [x] Determine if $obj->getShowInSearch() is relevant for outlet filtering (it is)
- [x] (Ingo) Investigate what it would take to index a field across models with the same name, so ShowInSearch rather than MyModel_ShowInSearch - Steve: there's no need for this as we'll be filtering all these results out before they get in the index anyway
- [x] (Ingo) add a warning label about creating non-deterministic getShowInSearch() implementations
- [x] Ensure inlet filtering applied to both cms save (dirty items) as well as solr_reindex
- [x] Ensure variantStateExcluded (draft?) functionality still works for all cases above
- [x] Get agreement with Cheddam about a combined approach with the canView() checks
- [x] Test with frameworktest records to ensure that reindex still functions OK
- [x] Update documentation
- [x] Write unit tests for 2x inlet filtering, determined to be not feasible for outlet filtering
- [x] Write release comms saying run solr_reindex, possibly commit straight to changelog
- [x] Investigate deleting $this->addFilterField('ShowInSearch') and related code used in outlet filtering - possibly a separate optional PR

### Links
https://silverstripeltd.slack.com/archives/CLXKD9X51/p1584670614347800

**Comment by emteknetnz** [comment]
**Ensuring that ShowInSearch is a filter field that is widely available**

(note: this is not the same as ensuring that ShowInSearch=0 record never get into the solr index)

Inheritance is:
```
class CwpSolrIndex extends CwpSearchIndex
abstract class CwpSearchIndex extends SolrIndex
abstract class SolrIndex extends SearchIndex
absract class SearchIndex extends ViewableData

CwpSolrIndex->init() { ... $this->addFilterField('ShowInSearch'); }
```

We could write the follow code to ensure this behaviour happens on across the board
```
SearchIndex->__construct() { ... $this->addFilterField('ShowInSearch'); }
```

**Comment by emteknetnz** [comment]
Creating a new page is the CMS and saving it will commit it to solr index immediately.  You don't even get given the chance to go to the Settings tab and untick 'Show In Search'? as you'll get a browser warning that you're navigating away from a form without saving it.

In the solr index it will have
```
        "SilverStripe\\CMS\\Model\\SiteTree_ShowInSearch": true,
        "_versionedstage": "Stage",
```

**Comment by emteknetnz** [comment]
To excluding DataObject with ShowInSearch = false from every getting into the index:

SearchUpdateProcessor:86 -
```
$objs = DataObject::get($base)->byIDs(array_keys($ids));
foreach ($objs as $obj) {
   ...
```

add the following:
```
if (isset($obj->ShowInSearch) && !$obj->ShowInSearch) {
    continue;
}
```

Stacktrace for updating solr index after click 'Save' in the CMS
```
Solr4Service_Core.php:35, SilverStripe\FullTextSearch\Solr\Services\Solr4Service_Core->addDocument()
SolrIndex.php:591, CWP\Search\Solr\CwpSolrIndex->_addAs()
SolrIndex.php:608, CWP\Search\Solr\CwpSolrIndex->add()
SearchUpdateProcessor.php:90, SilverStripe\FullTextSearch\Search\Processors\SearchUpdateImmediateProcessor->prepareIndexes()
SearchUpdateProcessor.php:142, SilverStripe\FullTextSearch\Search\Processors\SearchUpdateImmediateProcessor->process()
SearchUpdateImmediateProcessor.php:9, SilverStripe\FullTextSearch\Search\Processors\SearchUpdateImmediateProcessor->triggerProcessing()
SearchUpdater.php:188, SilverStripe\FullTextSearch\Search\Updaters\SearchUpdater::flush_dirty_indexes()
```

**Comment by chillu** [comment]
Yes, I'm not interested in solutions which index records that have ShowInSearch=false and them filter them out somehow. That's a bug, we need to fix it.

**Comment by chillu** [comment]
> Excluding DataObject with ShowInSearch = false from every getting into the index:

The code you added there seems to be aimed at deleting records with ShowInSearch=0 after they've been added already. I think there's two cases to cover: 1. A reindex for this object type should remove those records automatically (clean up after bad defaults), 2. new objects with ShowInSearch=0 shouldn't get into the index in the first place. 

Also, careful with doing `commit()` in a loop. The only reason that doesn't wreck search servers is that we actually ignore those commands in CWP, but on SC that's a bad idea usually (read up on `autoSoftCommit`, it's a bit of a rabbit hole)

**Comment by chillu** [comment]
Proposed ACs:

 * Records which have a ShowInSearch method or database property returning false are not indexed
 * This applies to built-in records (Page, File) as well as custom record definitions
 * This behaviour applies to both CWP and core module search\
 * The ShowInSearch value is inspected every time a record is saved (non-versioned) or published (versioned), and the index entry is updated accordingly
 * Existing index entries with ShowInSearch=0 can be pruned through a reindex
 * There is documentation both for CWP and generic module upgrade paths
 * Documentation stating that you need to filter out ShowInSearch during search request (rather than reindexing) is removed
 * Funtionality for filtering ShowInSearch during search requests is retained in order to minimise risk, but marked as deprecated and non-functional

**Comment by emteknetnz** [comment]
@chillu 
I'm believe we do actually need to delete the individual record from the index whenever it is updated from ShowInSearch=1 to ShowInSearch=0.  We cannot rely solely on developers running a reindex

If we do not delete it when it is updated, the following happen scenario happens:
- the CMS user adds a DataObject in the CMS and saves it.  Record is added to the solrindex with ShowInSearch=1
- the CMS user then unticks "Show in Search?" in the CMS and saves it.  The record in the solrindex is updated (but not deleted from) with ShowInSearch=0

So we haven't really solved much unless we delete records from the solrindex whenever ShowInSearch=0

Does this make sense?


, the following Reason being that it is added when you save a record with ShowInSearch=1 it is added to the index.  However, if w

**Comment by chillu** [comment]
> The ShowInSearch value is inspected every time a record is saved (non-versioned) or published (versioned), and the index entry is updated accordingly

Sorry, what I meant by this is "that's reflected by adding to or removing from the index"

**Comment by emteknetnz** [comment]
getShowInSearch() on inlet works as expected, the magic was well crafted back in the day

```
app/src/Page.php

public function getShowInSearch()
{
  // behaves as expected, "overrides" the SiteTree.ShowInSearch DB column
  // we can safely assume this will work in the absense of a <dataobject>.ShowInSearch column
}

public function getABC()
{
  return false;
}

isset($obj->ABC); // true
$obj->ABC; // false
isset($obj->ABCD); // false
$obj->ABCD; // null

```

**Comment by emteknetnz** [comment]
Seems like "outlet" filtering on the solr query isn't easily viable.  Reason being that the filtering on the 'ShowInSearch' column requires passing in the fully namespace column

In the solr index, it stored as
```
"SilverStripe\\CMS\\Model\\SiteTree_ShowInSearch": false
```

To filter this, I must adding an 'fq' value of 'SilverStripe\\CMS\\Model\\SiteTree_ShowInSearch:false' -  I cannot simply filter using a partial field name e.g. 'ShowInSearch:false' or '_ShowInSearch:false'

**Comment by emteknetnz** [comment]
This seems like a more viable place to do outlet filtering:

```
SolrIndex.php:777

        $results = new ArrayList();
        if ($res->getHttpStatus() >= 200 && $res->getHttpStatus() < 300) {
            foreach ($res->response->docs as $doc) {
                $result = DataObject::get_by_id($doc->ClassName, $doc->ID);
                if ($result) {
// new-code-start
                    if (isset($result-ShowInSearch) && !$result->ShowInSearch) {
                        continue;
                    }
// new-code-end
                    $results->push($result);
```

this also has the added benefit of calling ->getShowInSearch()

The only drawback with this approach is that it's on SolrIndex.php instead its parent class SearchIndex.php, though as previously discussed, we're assuming fulltextsearch implementations to be close to 100% solr4.  I don't feel as though there's a justification to make the effort to get this on to SearchIndex.php

Just to clarify what's being called

```
SolrIndex->search() {
  $service = $this->getService(); // Solr4Service_Core which is a fulltextsearch class
  ...
  $service->search(); // calls Apache_Solr_Service->search(), which is 3rd party module class and is the parent class of Solr4Service_Core.  At this point i'll make a request to the solr server
}
```

**Comment by emteknetnz** [comment]
**Add a warning label about creating non-deterministic getShowInSearch() implementations**

- A call to ->ShowInSearch is automatically at a module level in two places:
  a) before indexing so that ShowInSearch == false results are not indexed
  b) before returning results from the index, so any previously indexed results will not be returned
- Pages and Files have a ShowInSearch database column.
- Other DataObjects may have a ShowInSearch datbase column
- All DataObjects can "override" this database column with a custom getShowInSearch() function that returns true/false
- If you implement a custom getShowInSearch(), then this may mean that the database column 'ShowInSearch' in not used, meaning that 'Show In Search?' checkbox in the CMS admin found under Page > Settings does not function

**Comment by emteknetnz** [comment]
```
SolrReindexBase.php:266

protected function getRecordsInGroup(...

// ShowInSearch filter
foreach ($items as $item) {
  if (isset($item->ShowInSearch) && !$item->ShowInSearch) {
    $items->remove($item);
  }
}
```

Have tested this works with
/dev/tasks/Solr_Reindex
/dev/tasks/queue/Solr_Reindex - then manually run job in CMS
/dev/tasks/queue/Solr_Reindex - vendor/bin/sake dev/tasks/ProcessJobQueueTask


This is having some slightly unexpected results.
- I have 10 $items, one of which is ShowInSearch=0, so after this code I have 9 $items - this is correct
- However, the published record that was ShowInSearch=0 is then completely unpublished??

**Comment by emteknetnz** [comment]
Use ~2,200 pages created using frameworktest, seems like there's no impact of code in the pull-request on index time for doing a solr_reindex

fulltextsearch 3.6
1m 30s

fulltextsearch 3.6 branch
1m 25s

that 5 seconds is margin of error, could easily be me not being accurate with the stop watch

**Comment by chillu** [comment]
Yeah I wouldn't have expected a performance impact, since it already has that field in memory. The performance impact will be more pronounced with canView

**Comment by chillu** [comment]
Had a good call with Steve, here's some notes.

Principles (descending order of priority):
1. Minimise the possibility of new search implementations with security issues
2. Minimise additional complexity for devs to understand on top of already complex search API
3. Focus documentation on safe highlevel APIs, make it clear when "advanced" low-level APIs are referenced (and clarify dev responsibilities)
4. Clearly communicate changes and sanity checks to existing search implementations
5. Minimise performance impact on indexing
6. Minimise performance impact on search

Observations:
- canView() checks are already in SearchForm on base module
- canView() checks aren't implemented in CWP's SearchControllerExtension or the CwpSearchEngine it's using
- canView() checks aren't mentioned in CWP or base module docs (only on CWP in context of "Searching DataObjects")
- CWP docs reference a lowlevel API (SolrIndex->search()) in the basic docs (https://www.cwp.govt.nz/developer-docs/en/2/features/solr_search/basic_usage/)

Ingo's opinion:
- ShowInSearch and canView checks should be in the same place(s) (avoid more complexity)
- There needs to be a way to run the lowlevel API (SolrIndex->search()) without canView() checks, that's a valid use case for low level APIs
- For example, a dev might want to use a custom built batch canView checking across multiple object types rather than looping through each record
- The easiest way to achieve that is to leave this complexity out of lowlevel APIs, and consistently promote usage of highlevel APIs
- Analogy: We also don't tell you to retrieve your first DataObject via a raw SQL query in a Silverstripe tutorial
- Potentially doing canView() checks twice is a necessary evil on search (once in new module logic, once in existing custom logic)

**Comment by emteknetnz** [comment]
Have added two cucumber studio tests for ShowInSearch filtering https://studio.cucumber.io/projects/161118/test-plan/folders/1193287
